name: meteo_test
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^3.2.0
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.3
  flutter_animate: ^3.1.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: ^10.3.0
  from_css_color: 2.0.0
  google_fonts: ^4.0.1
  intl: 0.17.0
  json_path: ^0.4.2
  page_transition: ^2.0.9
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  simple_gradient_text: ^1.2.4
  smooth_page_indicator: 1.0.0+2
  sqflite: ^2.2.4+1
  timeago: ^3.3.0
  url_launcher: ^6.1.8
  location: ^4.4.0


dev_dependencies:

  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/